name: sports_complex_app
description: A sports complex application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^5.0.0
  rxdart: ^0.26.0

  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.4

  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1

  animations: ^2.0.0
  date_picker_timeline: ^1.2.3

  injectable: ^1.2.0
  get_it: ^6.0.0

  uuid: ^3.0.1
  firebase_auth_web: ^1.0.2
  intl: ^0.17.0-nullsafety.2

  json_annotation: ^4.0.0

  hive: ^2.0.0
  hive_flutter: ^1.0.0-nullsafety.0

  flutter_slidable: ^0.6.0-nullsafety.0

  font_awesome_flutter: ^9.0.0-nullsafety
  flutter_svg: ^0.21.0-nullsafety.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  injectable_generator: ^1.2.0

  surf_lint_rules: ^0.0.2-dev.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova/ProximaNova-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProximaNova/ProximaNova-Light.ttf
          weight: 200
        - asset: assets/fonts/ProximaNova/ProximaNova-Regular.ttf
          weight: 300
        - asset: assets/fonts/ProximaNova/ProximaNova-Semibold.ttf
          weight: 500
        - asset: assets/fonts/ProximaNova/ProximaNova-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProximaNova/ProximaNova-Extrabold.ttf
          weight: 700
        - asset: assets/fonts/ProximaNova/ProximaNova-Black.ttf
          weight: 800

flutter_intl:
  enabled: true
