name: sports_complex_app
description: A sports complex application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Code packages
  auto_route: ^2.0.2
  get_it: ^6.1.1
  injectable: ^1.3.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
#  provider: ^5.0.0
  rxdart: ^0.26.0
  uuid: ^3.0.4

  # Databases packages
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  cloud_firestore: ^1.0.7
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # UI packages
  animations: ^2.0.0
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  flutter_slidable: ^0.6.0-nullsafety.0
  font_awesome_flutter: ^9.0.0
  flutter_svg: ^0.22.0
  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators packages
  build_runner: ^2.0.1
  injectable_generator: ^1.3.0
  json_serializable: ^4.1.1
  auto_route_generator: ^2.0.1

  # Lint rules packages
  surf_lint_rules: ^1.0.0-dev.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova/ProximaNova-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProximaNova/ProximaNova-Light.ttf
          weight: 200
        - asset: assets/fonts/ProximaNova/ProximaNova-Regular.ttf
          weight: 300
        - asset: assets/fonts/ProximaNova/ProximaNova-Semibold.ttf
          weight: 500
        - asset: assets/fonts/ProximaNova/ProximaNova-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProximaNova/ProximaNova-Extrabold.ttf
          weight: 700
        - asset: assets/fonts/ProximaNova/ProximaNova-Black.ttf
          weight: 800

flutter_intl:
  enabled: true
